### ISSUE TITLE
Possibilità di mostrare la barra in assenza di cookie

### ISSUE THREAD

**Issue by vscorp** [ToX82/cookie-bar#1]
Avvio della Cookiebar anche in assenza di Cookies.
Ritorno della Cookiebar al riconoscimento di Cookies anche dopo l'accettazione, quindi eliminare i 30 giorni.
Aggiunta dei link alle Policy per servizi di terze parti tipo Adsense, Analitics, Addthis...

**Comment by ToX82** [comment]
Sono 3 funzioni diverse, per favore qui consideriamo solo la prima e per le altre apri due issue separate. Se puoi, modifica il testo della issue così è più semplice tenerne traccia.

L'avvio della cookiebar in assenza di cookie non è formalmente necessario ma mi è stato richiesto, direi che può essere una funzionalità opzionale utile. La segno per la prossima milestone.

**Comment by ToX82** [comment]
Fixed in [1.4](https://github.com/ToX82/cookie-bar/releases/tag/1.4.0)
