### ISSUE TITLE
Please provide minified version for jsDelivr

### ISSUE THREAD

**Issue by ping** [ToX82/cookie-bar#10]
I noticed this lib get auto updated into jsDelivr but there is no minified version.

Please consider offering a minified version for CDN hosting.
Using uglifyjs, there is almost a 50% saving in file size.

cookiebar-latest.js: 11464 bytes
cookiebar-latest.min.js: 6680 bytes

**Comment by ToX82** [comment]
I've just published a release which contains compressed JS and CSS files.

The website has been updated with the correct instructions, too.

Thanks!

**Comment by cemerson** [comment]
Does anyone know how the cookiebar-latest.min.js file gets generated for this project? When I try [MinifyAll](https://marketplace.visualstudio.com/items?itemName=josee9988.minifyall) in VSCode doesn't match the one in this repo.

**Comment by ToX82** [comment]
I'm using this extension: https://marketplace.visualstudio.com/items?itemName=HookyQR.minify
Which, under the hood, uses uglify-js

But it's not that important I guess, as long as it is minified.

Probably jsdelivr could do it itself though, so we could get rid of the manually minified version... I will have to try sooner or later :)

**Comment by cemerson** [comment]
Weird when I use that extension my status bar says "Minified 48%" when I save but nothing happens and the .min file isn't updated. May try another I guess. Thanks anyhow for the link.
