### ISSUE TITLE
Is it possible to stop scroll underneath the modal?

### ISSUE THREAD

**Issue by Allmedialab** [ToX82/cookie-bar#105]
Hi,
Would it be possible to stop the scroll underneath the modal? 
Regards & Thanks,
David

**Comment by ToX82** [comment]
It is technically possible, but I'd rather not do that the cookiebar, as not everyone would need or expect that behavior.

You still could do that in your website, adding something like this in your css:

    body.noscroll {
        overflow:hidden;
    }

Then, using JavaScript you could intercept the open modal event (maybe adding a listener on `cookie-bar-prompt-button`) and add the `.noscroll` class to `body`.
