### ISSUE TITLE
Privacy policy link in multiple languages difficult now 

### ISSUE THREAD

**Issue by Allmedialab** [ToX82/cookie-bar#106]
Hi,
Can't find a possibility in cookiebar to show the Privacy Policy link on a multi lingual website that leads to the proper language.
It recognizes the language and after clicking on the "Details" button the panel opens  in the proper language, but unfortunately its only contains the Privacy page link from the JavaScript init despite the fact that individual language links are added to the html pages. Of course the JavaScript init overrules everything with that one page.
Adding script links on other language pages to a other language Privacy page don't seem to initialize.
Is there any way to initialize the script again when going to an other page in a Ajaxify website?
Regards & Thanks,
David

**Comment by ToX82** [comment]
Hello David,
most websites have different ways to achieve what you are asking. I don't think that this issue could be solved by the cookiebar itself, but maybe you could create a new url which is a sort of placeholder url that you will link in the cookiebar:
`http://example.com/multilanguage-privacy-redirect`

If a user goes to that page (manually or using the cookiebar link), the server itself (using PHP, JavaScript or whatever language you are using) would know which language is currently in use, and redirect to the proper privacy page.

I hope this helps.
