### ISSUE TITLE
CookieBar wider than mobile device screen

### ISSUE THREAD

**Issue by pricey0069** [ToX82/cookie-bar#111]
Hey folks,

I have your cookie bar on my website. It looks great on tablets/laptops/desktops. But on mobile phones it goes out of the screen size and I have to scroll right to see it all. I used your main website to configure so I thought I would go back there and see if I can get it to fit the screen on mobile devices. I can't see anything that helps. I'm new and learning still so don't even know where to look after trying the configuration page on your site.

**Comment by ToX82** [comment]
There seems to be an issue with some CSS compatibility between your website and the cookie bar. If you are still having this issue, feel free to contact me with your website's url and I'll take a look at it.
