### ISSUE TITLE
Safari link is broken

### ISSUE THREAD

**Issue by LECtfield** [ToX82/cookie-bar#113]
The safari icon link broken. This take you to an Apple support page that no longer exists. I believe the correct page is https://support.apple.com/en-gb/guide/safari/sfri11471/mac

**Comment by LECtfield** [comment]
![image](https://user-images.githubusercontent.com/76161010/102481174-44794f80-4059-11eb-93e2-8c9e382b352e.png)

**Comment by ToX82** [comment]
It's fixed in 1.8.2, it will take a few hours/days for jsdelivr to propagate though.
Thanks!
