### ISSUE TITLE
Customize banner message

### ISSUE THREAD

**Issue by s-gbz** [ToX82/cookie-bar#115]
Hey there - thanks for creating this great piece of code!
I'd like to suggest a little more customizability options, since it'd be great to easily overwrite the default banner text.

I think there's a javascript passage that reads the banner texts from an html file.
Providing a little documentation how to work with it would be a great start.
Providing a new parameter inlcuding a language code would be pure luxus.

Hope this helps and it's not a duplicate (couldn't find related issues).
All the best!

**Comment by ToX82** [comment]
I'm sorry for the huge delay in this answer. Text customization is not actually doable when using the jsdelivr (hosted) version. You can easily download the project and use it locally through your web server, though.

Then you'd just need to edit the `.html` files in the `lang` directory.
