### ISSUE TITLE
Google Analytics cookies && Youtube Iframe Cookies

### ISSUE THREAD

**Issue by MROALI** [ToX82/cookie-bar#118]
Hello, 

Your lib doesn't empty Google analytics cookiies and youtube video cookies ?  Any idea how can i make it work ?

**Comment by ToX82** [comment]
Hi!
The cookieBAR, is a javascript solution, so it can't deal with external services, secure or http-only cookies. 

Anyway, you still have a couple of options that I can think of:
* preventively block those services. See https://cookie-bar.eu/#preventive-block
* listen for the "cookiebar" cookie value in your backend, and when it's "CookieDisallowed" you could delete those cookies. You can find an example here, if your backend is in PHP: https://stackoverflow.com/a/2310591/2619170
