### ISSUE TITLE
User consent log and export

### ISSUE THREAD

**Issue by RadimHercik** [ToX82/cookie-bar#121]
Based on the rules in the EU 2022 form, user consent and preferences should be recorded (such as IP, date and time, consent status) and it should be possible to export them if requested by the authorities.

**Comment by ToX82** [comment]
Hello @RadimHercik,
the cookiebar can't currently record those informations as it's a frontend only tool, but it should be easy to implement your own methods in order to save the user preferences. Please check out this page: https://cookie-bar.eu/#logging
