### ISSUE TITLE
Website with setup instructions is offline

### ISSUE THREAD

**Issue by victorbrender** [ToX82/cookie-bar#126]
The website that contains the setup instructions seems to be offline(permanently?).
See: [https://cookie-bar.eu/#configuration/](https://cookie-bar.eu/#configuration/)

Any chance we could add the setup instructions in the README so the website is not needed?
Thank you

**Comment by ToX82** [comment]
Hello Victor,
the website should be up and working, I'll fix it ASAP.

Thanks for letting me know
