### ISSUE TITLE
Increase bar height ?

### ISSUE THREAD

**Issue by gevv** [ToX82/cookie-bar#133]
Hello, what should I do to increase the bar height?
![sample](https://user-images.githubusercontent.com/5096676/207592779-b23b24ac-9880-4d09-a05b-2a5057d73385.png)

Thanks.

**Comment by ToX82** [comment]
Hello @gevv, you could add a custom rule to your website's CSS, something like this:

    #cookie-bar {
        padding: 20px 0;
    }

**Comment by gevv** [comment]
Thanks a lot, I added the code to the theme style file. It didn't work. Adding "!important" solved the problem. 

Best regards.
