### ISSUE TITLE
cookiebar-third-barty instead of cookiebar-third-party

### ISSUE THREAD

**Issue by playernine** [ToX82/cookie-bar#138]
Greetings.

I found a strange String the javascript:

Version 1.9.0

https://github.com/ToX82/cookie-bar/blob/c27762a0f299272d35a665564d27ab28daca09ec/cookiebar-latest.js#L542

setCookie('cookiebar-third-barty', document.getElementById('cookiebar-third-party').checked);

I think, thats an typo an should be:

setCookie('cookiebar-third-party', document.getElementById('cookiebar-third-party').checked);

:-)

In the Master: Version 1.10.2 
https://raw.githubusercontent.com/ToX82/cookie-bar/master/cookiebar.min.js
is Ok
but 
https://raw.githubusercontent.com/ToX82/cookie-bar/master/cookiebar-latest.min.js
is NOT OK.

I still find cookiebar-third-barty in the code.

Have a nice day.

**Comment by ToX82** [comment]
Hello @playernine , thank you for pointing this out! It has now been fixed :)
