### ISSUE TITLE
Want to donate but....

### ISSUE THREAD

**Issue by Allmedialab** [ToX82/cookie-bar#140]
Hi,

Can you please give me your PayPal email address? Then I can send you the donation from without my own PayPal account. The links on your site don't work for me.

Thanks,
David

**Comment by ToX82** [comment]
Hello David,
thank you for telling me! I've fixed the PayPal link on cookiebar's website.
You will see the PayPal link on this project's home page too, there is a "Sponsor this project" section. :)

Have a great day!

**Comment by Allmedialab** [comment]
Hi Emanuele,

Donated € 100,- 

But did not receive any reply. Did you receive it?

Regards,

David

**Comment by ToX82** [comment]
Hello David, thank you for your donation! 
Could you give me your email address by sending me a mail? You'll see my address here: https://emanuele.itoscano.com/nodes/view/63_contacts

P.S. I apologize for my late reply but I'm currently on vacation.
