### ISSUE TITLE
HTTPS 

### ISSUE THREAD

**Issue by themichael123** [ToX82/cookie-bar#17]
Hi Again !

sorry for all these issues. The Chrome Developer Console brings up this error message:

"URL" was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.telize.com/geoip'. This request has been blocked; the content must be served over HTTPS.

**Comment by ToX82** [comment]
My bad, I typed the address with the http: protocol... I've released a fix for this problem, it should be ok now. Sorry for this!
