### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by themichael123** [ToX82/cookie-bar#18]
Hi!

telize is also timing out most of the time.

**Comment by ToX82** [comment]
Hi, there still is a 1500ms timeout for geoip localization. Telize is much faster than freegeoip but still it could timeout in some conditions (slow internet connections, mostly). 
The only way to limit this timeout would be to raise the timeout itself to more than 1500ms, and I don't think if this would be a good idea.
I will leave this issue open with the question tag, let's see what other people think.

**Comment by ToX82** [comment]
I'm closing this since we are not using telize anymore, and freegeoip seems to be much faster now.
