### ISSUE TITLE
Errors in French translation

### ISSUE THREAD

**Issue by jacmaes** [ToX82/cookie-bar#19]
Great script, but the French translation could be much improved with a few quick changes. As a native speaker, here are my suggested changes:
- Line 7 and 8:
  Ce site utilise des cookies pour améliorer l'expérience de navigation et fournir des fonctionnalités supplémentaires. Ces données ne seront pas utilisées pour vous identifier ou vous contacter.
- Line 11 and 15:
  (...) la politique (...)
- Line 19:
  Pour savoir comment ce site utilise les cookies ou la technologie du localStorage, lisez notre politique de confidentialité.
- Line 21:
  (...) vous consentez à ce que ce site sauvegarde (...)
- Line 26:
  Pour en savoir plus sur les cookies et le localStorage, visitez le site de la  (...)
- Line 45:
  Ce site utilise des cookies pour améliorer l'expérience de navigation et fournir des fonctionnalités supplémentaires.
- Line 46:
  En savoir plus (instead of "Détails")

**Comment by ToX82** [comment]
Merci beaucoup jacmaes!
I've published a 1.5.6 release containing your improvements.
