### ISSUE TITLE
Geolocalizzazione

### ISSUE THREAD

**Issue by vscorp** [ToX82/cookie-bar#2]
Geolocalizzazione dei soli paesi afflitti dalla normativa, quindi escludere il resto del mondo dalla visualizzazione della barra.

**Comment by grigio** [comment]
Per la geolocalizzazione si potrebbe usare https://freegeoip.net , ma così facendo bisognerebbe aspettare la risposta dei loro server prima di fare alcunché

**Comment by ToX82** [comment]
Buona idea, non conoscevo quel servizio. Faccio qualche prova, se non rallenta troppo è una possibilità.

**Comment by vscorp** [comment]
Anzichè bloccare gli IP non europei fare il giro più breve permettendo quelli europei, ci sono diverse liste di IP: http://www.ipdeny.com/ipblocks/

**Comment by grigio** [comment]
Il problema di una lista statica é che periodicamente va aggiornata. Comunque una politica "scroll to accept" dovrebbe essere accettabile un po' da tutti.
Sarebbe buffo che la lista degli ip europei pesasse più di cookie-bar stesso

**Comment by ToX82** [comment]
In realtà la questione è abbastanza semplice. La url https://freegeoip.net/json/ mi restituisce già il paese di provenienza dell'utente nel campo "country_code" (e la lista dei paesi che aderiscono alla cookie law non è molto lunga), e volendo potrei addirittura prendere una scorciatoia e leggere la prima parte di "time_zone", che mi restituisce già Europe, Asia, America ecc. Ho optato per la prima soluzione perché mi sembra più ottimale, a breve dovrei riuscire a fare un update.

**Comment by grigio** [comment]
Credo il campo giusto sia il country_code, perché non tutti in Europa sono in EU e non tutti i territori dell'Unione Europea sono in Europa

**Comment by vscorp** [comment]
Quali sono i paesi in cui si deve rispettare questa legge? l'importante è farla apparire solo li.

**Comment by ToX82** [comment]
http://cookiepedia.co.uk/cookie-laws-across-europe qua c'è l'elenco con tanto di spiegazioni (ovviamente, ogni paese l'ha interpretata a modo suo nonostante fosse una legge europea)

**Comment by ToX82** [comment]
Buone notizie e cattive notizie. Il controllo è facilmente implementabile e funziona, ma non è sempre veloce. Durante i miei test sono passato da una media di 500 ms fino a... 22secondi.

**Comment by ToX82** [comment]
Ho implementato un timeout di 3 secondi per ovviare a questo problema, chiudo!
