### ISSUE TITLE
Telize has been shut down

### ISSUE THREAD

**Issue by themichael123** [ToX82/cookie-bar#20]
Hi !

Telize has been shut down according to the website.

**Comment by ToX82** [comment]
This is a really bad news. Any hint for a free alternative?

**Comment by ToX82** [comment]
I have found a couple of services, but I need furter investinations for limitations, latency etc... any help would be very welcome!

http://ip-api.com/json
http://ipinfo.io/json

**Comment by themichael123** [comment]
There will always be an issue of reliability if a free service is used. 

Telize used this database: http://geolite.maxmind.com/download/geoip/database/GeoLite2-City-CSV.zip

Implementing this CSV database in an AWS lambda function would probably take a couple of days.

**Comment by ToX82** [comment]
I'm sorry but I am not going create a new web service for this, as this is a free plugin and I can't invest more than I am already doing.

I switched back to freegeoip which seems to be quite reliable now, but I would greatly appreciate if someone could create something ad hoc.
