### ISSUE TITLE
Option to nofollow for search engines

### ISSUE THREAD

**Issue by utilsites** [ToX82/cookie-bar#27]
It's possible to include the attribute rel="nofollow" in the a links? 
To not follow by search engines.

**Comment by ToX82** [comment]
This is a good idea indeed, I have published an update with that attribute for all the links. It is still not in a release though, I will publish a new release with this and a couple other minor fixes ASAP.

**Comment by utilsites** [comment]
Ok thanks. I think the engines should not index this cookie related texts.
I will wait for that release.
