### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by JeppeDonslund** [ToX82/cookie-bar#33]
I have made a Danish language file. How can it be integrated?

**Comment by ToX82** [comment]
Hi! You could make a pull request, so that I can merge it. If you don't have your own fork on github, anyway, please contact me through the chat that you can see on cookie-bar.eu, you will send me the file over there. Thanks!

**Comment by JeppeDonslund** [comment]
Hi 

I con't know how to do taht. Maybe I shold, but I ont't. 

Jeppe

ToX82 skrev den 19.05.2016 12:16:

> Hi! You could make a pull request, so that I can merge it. Thanks! 
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]

## Links:

[1] https://github.com/ToX82/cookie-bar/issues/33#issuecomment-220283999

**Comment by ToX82** [comment]
No worries, just come to cookie-bar.eu and use the chat on the bottom right, you can send me the file over there.

**Comment by ToX82** [comment]
Translation merged! I'm closing this
