### ISSUE TITLE
generator does not correctly escape the script URL

### ISSUE THREAD

**Issue by pinhead84** [ToX82/cookie-bar#43]
My HTML editor complains about the HTML snippet, that was created with your generator at [cookie-bar.eu](http://cookie-bar.eu). For example the snippet

```html
<script type="text/javascript" src="//cdn.jsdelivr.net/cookie-bar/1/cookiebar-latest.min.js?forceLang=de&theme=grey&tracking=1&remember=100&privacyPage=%2Fprivacy"></script>
```

does not have a correctly escaped URL. I guess correct should be:

```html
<script type="text/javascript" src="//cdn.jsdelivr.net/cookie-bar/1/cookiebar-latest.min.js?forceLang=de&amp;theme=grey&amp;tracking=1&amp;remember=100&amp;privacyPage=%2Fprivacy"></script>
```

**Comment by ToX82** [comment]
I'm not sure about fixing this. It's a minor and non-breaking issue but it could potentially create more problems if fixed.

As an example, when copying the url to some fancy (bugged) html wysiwyg editor that automatically converts the `&` to `&amp;` could convert the `&amp;` into `&amp;amp` :). It happened to me in the past, I'm not even sure that there still are that kind of dumb editors but...
