### ISSUE TITLE
Slovenian translation still not on CDN

### ISSUE THREAD

**Issue by vkocjancic** [ToX82/cookie-bar#52]
Sorry, to bother you, but CDN still doesn't have Slovenian translation. Can you check what is going on?

**Comment by ToX82** [comment]
I'm afraid it's the jsdelivr caching system which is a bit slow. I hope that everything will be updated in a few days.
Meanwhile, you can use latest specific version (1.5.24 as of now) instead of `latest`.

    https://cdn.jsdelivr.net/cookie-bar/1.5.24/cookiebar-latest.js

My advice is to switch back to using latest as soon as it's updated though.

    https://cdn.jsdelivr.net/cookie-bar/latest/cookiebar-latest.js

**Comment by vkocjancic** [comment]
changed url from https://cdn.jsdelivr.net/cookie-bar/1/cookiebar-latest.min.js (on cookie-bar.eu site) to https://cdn.jsdelivr.net/cookie-bar/latest/cookiebar-latest.min.js and now it works.

Cheers.
