### ISSUE TITLE
cookieBAR always showing

### ISSUE THREAD

**Issue by chrona** [ToX82/cookie-bar#65]
Maybe I'm understanding this wrong, but on the website the plugin is listed as:

> It shows up when needed and stay silent when not: If a website has some cookies or localStorage data set then the bar is shown, otherwhise nothing happens.

For testing purposes I hosted a empty HTML file with nothing except the code produced by the configurator:

`<!-- test.html -->`
`<script src="https://cdn.jsdelivr.net/npm/cookie-bar/cookiebar-latest.min.js?forceLang=de&noGeoIp=1&top=1&hideDetailsBtn=1"></script>`

But for some reason I still get the cookie notice no matter what. I would have thought that the bar would now be hidden unless I would set a cookie before.

**Comment by ToX82** [comment]
Indeed, it should work like you have understood. Can you try to see what happens if you remove the noGeoIp parameter?

**Comment by chrona** [comment]
Unfortunately it still shows, I also tried it without any parameters at all with the same results.

**Comment by ToX82** [comment]
It looks like there's a bug. I'll try to investigate asap.

**Comment by LRH539** [comment]
Probably resolved by #73.

**Comment by ToX82** [comment]
I'm sorry for the huge delay but I've finally solved this bug. Please let me know if you still notice something wrong (it could take a few days before the modifications will propagate though).
