### ISSUE TITLE
FreeGeoIP will be no longer Free. What can we switch to?

### ISSUE THREAD

**Issue by ToX82** [ToX82/cookie-bar#66]
The FreeGeoIP team has announced that their API will be discontinued starting from the 1st of July 2018. They are switching to a new geoip service but the free plan will have a 10.000 request limit, so it's not viable for cookiebar. Moreover, an API Key would be needed and I'd like to avoid it.

Do you know another similar service that cookiebar could use? TBH we wouldn't even need precise geolocation, as the cookiebar only needs to detect the user's country code.

Here are some free services that I've found:

http://ip-api.com/
http://geoip.nekudo.com/
...

Any suggestions?

**Comment by LRH539** [comment]
Probably resolved by #73.

**Comment by freegeoipapp** [comment]
I've setup
https://freegeoip.app

- HTTPS (no HTTP, sorry - it's 2018)
- Rate limit of 15000/hour as before for FREE, guaranteed
- No logs, no analytics - privacy alway in mind
- Continued development for features like bulk lookup and other data sources

no changes needed other than the TLD ;) (it's the same API)

**Comment by ToX82** [comment]
We have switched to ipdata.co. Thanks anyway for your suggestion!

p.s. do you have a contact or a github page? I'd like to give you a few code samples for your home page...

**Comment by ToX82** [comment]
Eventually, I'll switch to your service freegeoip.app since ipdata.co has changed their policy...
