### ISSUE TITLE
GDPR-compliance / GeoIP - Auto Opt-In for non-EEA visitors.

### ISSUE THREAD

**Issue by claudio-vellage** [ToX82/cookie-bar#72]
I am currently using cookie-bar on my website to prevent AdSense ads from showing, because this is required to comply with the AdSense TOS. Because my ads are Opt-In now for all customers, this has largely impacted my page's ad revenue. A large part of my visitors is based in the US and India, so they are not affected by the GDPR and I could show them ads without requiring consent.

Unfortunately, right now cookie-bar is either always showing (no GeoIP) or only showing for EEA visitors (GeoIP). In the latter case, if I want to check if the Opt-In cookie has been set by cookie-bar, this would obviously fail, because cookie-bar has never been loaded, thus no cookie has been set.

I would now have to use an additional GeoIP plugin to determine the visitors location, but since cookie-bar already does GeoIP identification, it would be easiest if cookie-bar still sets the CookieAllowed cookie if the GeoIP verification determined that the visitor is located outside of the EEA, i.e. Opt-In for all non-EEA visitors. I'll gladly help implementing this feature.

**Comment by LRH539** [comment]
Probably resolved by #73.

**Comment by ToX82** [comment]
I'm closing this issue, we can continue in the Pull Request: https://github.com/ToX82/cookie-bar/pull/73
