### ISSUE TITLE
Cookie-bar doesn't work with Bootstrap theme

### ISSUE THREAD

**Issue by zambala** [ToX82/cookie-bar#74]
It seems Cookie Bar doesn't show up on a popular Bootstrap Theme (Twitter Bootstrap theme); my website is Drupal 7, Cookie bar used to work and still works with another theme, but I recently switched to Bootstrap theme and it doesn't work, if I change theme back, it shows.....

Bootstrap theme is also using cdn.jsdelivr.net;
Cookie-Bar-Master - I have downloaded locally long time ago in a separate folder; it used to work, but now I don't know what to do...

**Comment by zambala** [comment]
Update:
now it seems to work when I write it specifically in theme.info file for Bootstrap theme, like:

scripts[] = cookie-bar-master/cookiebar-latest.min.js

this wasn't needed with other themes...

**Comment by ToX82** [comment]
Hi @zambala, honestly I don't know what that behavior could be due to... Thank you for sharing the solution anyway!
