### ISSUE TITLE
Should the &always parameter be the default behavior?

### ISSUE THREAD

**Issue by page6de** [ToX82/cookie-bar#76]
It seems as the Cookie Banner does not show up in Firefox or Chrome (on Mac) anymore, neither in Safari on iOS. No "cookiebar: CookieAllowed" Cookie is set so far. Maybe you can take a look at that.
Take a look at: https://www.page6.de/cookie.html

**Comment by ToX82** [comment]
It seems that there is no cookie nor localstorage set in that page. This could be the reason why the cookiebar doesn't show up. 

In fact, the default behavior of the cookiebar is to stay silent if there are no (js readable) cookies or localstorage.

Could you try adding the &always=1 parameter in the cookiebar script?

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/cookie-bar/cookiebar-latest.min.js?always=1"></script>

**Comment by page6de** [comment]
Thank you, that works! With ?always=1 it is displayed in Firefox and Chrome. It now sets the Cookie if you click "Allow Cookies" and then works as expected. 
I think, this behaviour might be worth a note, because it's really important that you can trust in that. I've added this to a site, it worked in Safari on Mac, and so I thought it would in all other browsers as well. Just weeks after I realised that it does not and I'm happy that I've seen this instead of a layer. ;)
But thanks anyway for the fast reply and for creating and sharing this script!

**Comment by ToX82** [comment]
I am wondering if it should be the default behavior indeed...

**Comment by bricebou** [comment]
Hum... I was confused also with this behavior but it's the most logic behaviour :-)
I think the confusion is linked to the "preventive" option: if it's set to true, your cookies aren't loaded and the cookiebar doesn't show... 
So, the `&always=1` parameter should be added by default when the `preventive` parameter is set to true.
No ?

**Comment by ToX82** [comment]
The thing is that the cookieBAR remains hidden when it doesn't detect any cookie. This is good in theory.

BUT, being a javascript plugin it can only detect HHTP cookies but it can't see all of the other cookies that could be present (secure cookies, non HTTP cookies...)

This could be a bit misleading: a website could have some cookies indeed, but the cookiebar doesn't detect them so the cookie advice is not shown. That is why most of the websites should use the `&always` parameter. Should we use that parameter as the default behavior?

**Comment by bricebou** [comment]
Hum... right ! so I guess `&always` parameter should be default behavior :-)

And suddenly, a question comes to mind: if you have downloaded and installed this plugin onto your website, why would you want to hide it ?
Do you have cases in mind ?

**Comment by ToX82** [comment]
That would be useful for really small websites that are unsure wether they use cookies or not (eg. they only set cookies when the users trigger a specific action) and they don't want to show the cookiebar when it's not needed.

And I like it to be that way in theory, but those kind of websites could be edge cases indeed, as the majority of websites do use cookies...

Maybe we could do the reverse check: always show the cookiebar by default, unless the site owner specifies a `?checkforcookies` option

What do you think?

**Comment by bricebou** [comment]
I'm not sure I've understood your last idea; but, given what you said before:

> BUT, being a javascript plugin it can only detect HHTP cookies but it can't see all of the other cookies that could be present (secure cookies, non HTTP cookies...)

and 

> That would be useful for really small websites that are unsure wether they use cookies or not

I think it would be best solution to set the `&always` parameter to "true" by default; and only the most "concerned", "aware" web editors would set it to false if needed ?

**Comment by ToX82** [comment]
Indeed :)

I'll make the `&always` parameter pre-selected on the configurator then, adding a tooltip explaining what that checkbox means and why it's pre-selected.

Do you think this message is clear enough?

> The cookieBAR has the possibility to stay silent if there are no javascript readable cookies or localstorage.
> This could be an issue if you have non HTTP or SECURE cookies, which are not detectable by Javascript.
> 
> If unsure, keep this checkbox checked :)

**Comment by bricebou** [comment]
That seems pretty clear to me :-)

--
Brice Boucard

**Comment by ToX82** [comment]
`&always` is now the default behavior!
