### ISSUE TITLE
cookieBAR and composer

### ISSUE THREAD

**Issue by bricebou** [ToX82/cookie-bar#77]
Hi, 

I've worked on a cookieBAR plugin for Pico (http://picocms.org/). Here it is: https://github.com/bricebou/PicoCookieBAR

It would be great if you made cookieBAR available through PHP composer, through https://packagist.org.

Thanks for your script !

**Comment by ToX82** [comment]
Hi! Even though I often use packagist, it seems to be more aimed to PHP projects, while the cookieBAR is a pure javascript plugin.

In this case, I'd suggest you to use `npm` instead, and leave composer for PHP stuff :)

**Comment by bricebou** [comment]
Thanks ! I've updated my PicoCookieBAR plugin (https://github.com/bricebou/PicoCookieBAR/commit/bb0167b62f9e9955f50d60a4b6a363ef8d28b245).
