### ISSUE TITLE
Add options to choose an cookie level

### ISSUE THREAD

**Issue by scysys** [ToX82/cookie-bar#83]
Add options to choose an cookie level

Level 1: Only needed Cookies
Level 2: Statistical Cookies
Level 3: Advertising Cookies

and so on

**Comment by ToX82** [comment]
I like the idea! It could be optional though: 
The default behavior will be the same (accept or deny all cookies)
If a website owner wants the "selective cookie selection" the choice would be between:

* technical cookies
* tracking cookies
* third party cookies

What do you think?

**Comment by scysys** [comment]
Sure, this must be optional.

If an user accept cookies on an website, cookiebar should allowed all cookie levels.
If the website owner setup multiple cookie levels, user should have the option to choose which cookies he wants to activate.

So website owner can easily control the cookies based on user selection like:

`    if (cookieValue == 'CookieAllowed-All') {`

`    if (cookieValue == 'CookieAllowed-Technical') {`

`    if (cookieValue == 'CookieAllowed-Tracking') {`

and so on
