### ISSUE TITLE
"privacy policy" link sits next to "details" link without separation

### ISSUE THREAD

**Issue by skyegecko** [ToX82/cookie-bar#89]
When a custom Privacy policy page is configured, the link to this page is place right next to the existing Details link without a clear separation between the two. Without hovering with the mouse it is unclear that there are two links present. Additionally the bar reads awkwardly due to the two phrases not being separated.

![image](https://user-images.githubusercontent.com/2513484/54165231-19af9f80-4460-11e9-8261-672edbe648a7.png)

**Comment by ToX82** [comment]
Fixed! I've added some horizontal padding to those links
