### ISSUE TITLE
Not showing on certain devices?

### ISSUE THREAD

**Issue by lettie16** [ToX82/cookie-bar#91]
The cookie bar is not displaying on certain devices:

Microsoft Surface, Windows 10, Chrome
iphone 6 ios 12.1

And Microsoft Surface using explorer closes the cookie bar when using the browser back button?

**Comment by ToX82** [comment]
I can't test it since I don't have that device. Are you seeing the problem even on cookie-bar.eu?

**Comment by motionmountain** [comment]
On iphone/ios with Safari there is indeed no message appearing on cookie-bar.eu

**Comment by Allmedialab** [comment]
I can test it! I have Xcode running on my iMac with all IOS devices in the simulator, but first I need to make the script working from my server. Tried to connect the script and uploaded all the files, but nothing happens. With the link configuration it works without a problem, but I need further editing in the HTML files.

**Comment by ToX82** [comment]
I couldn't see this issue on any freshly installed browser, but I've noticed that the cookiebar is indeed not shown when some adblockers are in use. Maybe this was the issue here?
