### ISSUE TITLE
Snippet to check cookie value throws error

### ISSUE THREAD

**Issue by cosenmarco** [ToX82/cookie-bar#95]
The snippet
```js
 cookieValue = document.cookie.match(/(;)?cookiebar=([^;]*);?/)[2];
```
throws error `Uncaught TypeError: Cannot read property '2' of null` when `cookiebar` cookie is not present in Chrome 74.0.3729.108

I'd suggest to change that to the following:
```js
let matches = document.cookie.match(/(;)?cookiebar=([^;]*);?/);
let cookieValue = Array.isArray(matches) ? matches[2] : '';
```
note this may not be compatible with older browsers...

**Comment by ToX82** [comment]
Hello Marco, I'm closing this issue as it has been fixed in a previous commit.
